language: c
os: linux
dist:
    - bionic

addons:
    apt:
        update: true
        packages:
            - sphinx-common
            - latexmk
            - texlive-latex-recommended
            - texlive-latex-extra
            - python3-pip
            - python3-wheel
            - python3-setuptools
            - bash
            - git

jobs:
    include:
        - stage: buid_doc
          script:
              # Install the smartleia Python package
              - git clone https://github.com/cw-leia/smartleia.git
              - cd smartleia && pip3 install -r requirements.txt
              - cd smartleia && python setup.py install
              # Take care of the documentation now
              - pip3 install -U wheel
              - pip3 install -U setuptools
              - pip3 install -r requirements.txt
              # Build HTML doc
              - make html
              # Build PDF doc
              - make latexpdf

notifications:
  email:
    recipients:
      - leia@ssi.gouv.fr
    on_success: never
    on_failure: always
    on_pull_requests: always

